name: Build Electron App

on:
  push:
    branches:
      - main
      - mac
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Ajuste conforme necessário

    - name: Install dependencies
      run: npm install

    - name: Build the Electron App
      run: npm run mac

    # Opcional: Salvar como Artefato para download direto do GitHub Actions
    - name: Upload Electron Installer as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: electron-installer
        path: dist/
