name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Ajuste conforme necessário

    - name: Install dependencies
      run: npm install

    - name: Build the Electron App
      run: npm run mac

   

    # Opção 1: Salvar como Artefato
    - name: Upload Electron Installer as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: electron-installer
        path: dist/

    # Opção 2: Criar uma Release e Anexar o Instalador
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: 'v1.0.0'
        release_name: 'Release v1.0.0'
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Installer to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/installer-name.dmg  # Ajuste conforme necessário
        asset_name: installer-name.dmg
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
