name: Build Electron App

on:
  push:
    branches:
      - main
      - mac
  
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Ajuste conforme necessário

    - name: Install dependencies
      run: npm install

    - name: Build the Electron App
      run: npm run mac

    - name: Package with Electron Builder
      run: npx electron-builder --mac --win --linux

    # Upload macOS installer as artifact
    - name: Upload macOS Installer
      uses: actions/upload-artifact@v3
      with:
        name: macOS-installer
        path: dist/*.dmg

    # Upload Windows installer as artifact
    - name: Upload Windows Installer
      uses: actions/upload-artifact@v3
      with:
        name: windows-installer
        path: dist/*.exe

    # Upload Linux installer as artifact
    - name: Upload Linux Installer
      uses: actions/upload-artifact@v3
      with:
        name: linux-installer
        path: dist/*.AppImage
